[package]
name = "memstats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
argh = "0.1"
ctrlc = "3"
env_logger = "0.9"
log = "0.4"
regex = "1.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[workspace]
