[package]
name = "libva"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
anyhow = "*"
bitflags = "1"
log = { version = "0", features = ["release_max_level_debug"] }

[build-dependencies]
pkg-config = "*"

[dev-dependencies]
crc32fast = "1.2.1"
