[package]
name = "crosvm_control"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
base = { path = "../base" }
vm_control = { path = "../vm_control" }
libc = "0.2.65"

[build-dependencies]
anyhow = "*"
cbindgen = "0.24.3"
cc = "*"
tempfile = "*"
