[package]
name = "hypervisor"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
haxm = []
whpx = []
gdb = ["gdbstub", "gdbstub_arch"]

[dependencies]
bit_field = { path = "../bit_field" }
bitflags = "1"
data_model = { path = "../common/data_model" }
downcast-rs = "1.2.0"
enumn = "0.1.0"
fnv = "1"
gdbstub = { version = "0.6.3", optional = true }
gdbstub_arch = { version = "0.2.4", optional = true }
libc = "*"
memoffset = "0.6"
once_cell = "1.7"
serde = { version = "1", features = [ "derive" ] }
sync = { path = "../common/sync" }
base = { path = "../base" }
vm_memory = { path = "../vm_memory" }

[target.'cfg(unix)'.dependencies]
kvm = { path = "../kvm" }
kvm_sys = { path = "../kvm_sys" }

[target.'cfg(windows)'.dependencies]
thiserror = "*"
winapi = "*"
win_util = { path = "../win_util" }

[target.'cfg(windows)'.dev-dependencies]
tempfile = "*"
