[package]
name = "aarch64"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
gdb = ["gdbstub", "gdbstub_arch", "arch/gdb", "hypervisor/gdb"]

[dependencies]
arch = { path = "../arch" }
cros_fdt = { path = "../cros_fdt" }
data_model = { path = "../common/data_model" }
devices = { path = "../devices" }
gdbstub = { version = "0.6.3", optional = true }
gdbstub_arch = { version = "0.2.4", optional = true }
hypervisor = { path = "../hypervisor" }
kernel_cmdline = { path = "../kernel_cmdline" }
kernel_loader = { path = "../kernel_loader" }
kvm = { path = "../kvm" }
kvm_sys = { path = "../kvm_sys" }
libc = "*"
memoffset = "0.6"
minijail = "*"
remain = "*"
resources = { path = "../resources" }
sync = { path = "../common/sync" }
base = { path = "../base" }
thiserror = "*"
vm_control = { path = "../vm_control" }
vm_memory = { path = "../vm_memory" }
