[package]
name = "vm_control"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
balloon = []
gdb = ["gdbstub", "gdbstub_arch"]
gpu = []
registered_events = ["protos/registered_events"]
swap = ["swap/enable"]

[dependencies]
anyhow = "*"
balloon_control = { path = "../common/balloon_control" }
base = { path = "../base" }
cfg-if = "*"
data_model = { path = "../common/data_model" }
gdbstub = { version = "0.6.3", optional = true }
gdbstub_arch = { version = "0.2.4", optional = true }
hypervisor = { path = "../hypervisor" }
libc = "*"
once_cell = "1.7.2"
protos = { path = "../protos", optional = true }
remain = "*"
resources = { path = "../resources" }
rutabaga_gfx = { path = "../rutabaga_gfx"}
serde = { version = "1", features = [ "derive" ] }
serde_json = "*"
serde_keyvalue = { path = "../serde_keyvalue", features = ["argh_derive"] }
swap = { path = "../swap" }
sync = { path = "../common/sync" }
thiserror = "*"
vm_memory = { path = "../vm_memory" }

[target.'cfg(windows)'.dependencies]
winapi = "*"
