[package]
name = "tube_transporter"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"


[dependencies]
base = { path = "../base" }
data_model = { path = "../common/data_model" }
rand = "0.8"
thiserror = "1.0.20"
serde = { version = "1", features = [ "derive" ] }
serde_json = "*"
win_util = { path = "../win_util"}
winapi = "*"
