[package]
name = "net_util"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"
build = 'build.rs'

[features]
guest-to-host-net-loopback = []
slirp = ["libslirp-sys", "pcap-file"]
slirp-debug = ["slirp"]
slirp-ring-capture = ["slirp"]

[dependencies]
base = { path = "../base" }
cfg-if = "1.0.0"
cros_async = { path = "../cros_async" }
libc = "0.2"
pcap-file = { version = "1.1.0", optional = true }
remain = "0.2"
serde = { version = "1", features = [ "derive" ] }
smallvec = "1"
thiserror = "1"
virtio_sys = { path = "../virtio_sys" }
zerocopy = { version = "0.7", features = ["derive"] }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
net_sys = { path = "../net_sys" }

[target.'cfg(windows)'.dependencies]
metrics = { path = "../metrics" }
winapi = { version = "0.3", features = ["everything", "std", "impl-default"] }
libslirp-sys = { version = "4.2.1", optional = true }

[build-dependencies]
anyhow = "1"
prebuilts = { path = "../prebuilts" }

[dev-dependencies]
serde_json = "1"
