[package]
name = "data_model"
version = "0.1.0-alpha.0"
authors = ["The Chromium OS Authors"]
edition = "2021"
include = ["src/**/*", "Cargo.toml"]
description = "[highly unstable] data model for virtualization"
license-file = "LICENSE"

[dependencies]
static_assertions = "1.1"
cfg-if = "1.0.0"
libc = "0.2.116"
remain = "0.2"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.20"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["everything", "std", "impl-default"] }
