[package]
name = "libvda"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"
links = "vda"

[features]
libvda-stub = []

[dependencies]
enumn = "0.1.0"
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
