[package]
name = "e2e_tests"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dev-dependencies]
anyhow = "*"
fixture = { path = "fixture" }
rand = "0.8"
tempfile = "3"
prebuilts = { path = "../prebuilts" }
base = { path = "../base" }

[features]
direct = []
