[package]
name = "snapshot"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]

[dependencies]
anyhow = "1"
base = { path = "../base" }
crypto = { path = "../vendor/generic/crypto", package = "crypto_generic" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
