[package]
name = "p9"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[target.'cfg(unix)'.dependencies]
libc = "*"
serde = { version = "*", features = [ "derive" ] }
wire_format_derive = { path = "wire_format_derive", version = "*" }

[features]
trace = []


