[package]
name = "x86_64"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
gdb = ["gdbstub_arch", "arch/gdb"]
direct = ["arch/direct", "devices/direct"]
seccomp_trace = []

[dependencies]
acpi_tables = {path = "../acpi_tables" }
arch = { path = "../arch" }
anyhow = "*"
cfg-if = "1.0.0"
chrono = "*"
cros_fdt = { path = "../cros_fdt" }
data_model = { path = "../common/data_model" }
devices = { path = "../devices" }
gdbstub_arch = { version = "0.2.4", optional = true }
hypervisor = { path = "../hypervisor" }
jail = { path = "../jail" }
kernel_cmdline = { path = "../kernel_cmdline" }
kernel_loader = { path = "../kernel_loader" }
libc = "*"
once_cell = "1.7.2"
rand = "0.8"
remain = "*"
resources = { path = "../resources" }
sync = { path = "../common/sync" }
thiserror = "*"
base = { path = "../base" }
vm_control = { path = "../vm_control" }
vm_memory = { path = "../vm_memory" }
zerocopy = "*"

[target.'cfg(unix)'.dependencies]
minijail = "*"

[target.'cfg(target_os="linux")'.dependencies]
swap = { path = "../swap", optional = true }
