[package]
name = "swap"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
anyhow = "*"
base = { path = "../base" }
data_model = "*"
libc = "*"
minijail = "*"
remain = "*"
serde = { version = "1", features = [ "derive" ] }
serde_json = "*"
sync = { path = "../common/sync" } # provided by ebuild
tempfile = "*"
thiserror = "*"
userfaultfd = "0.5.0"
vm_memory = { path = "../vm_memory"}
