[package]
name = "swap"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

# The process tests will use fork, which requires a custom test harness to enforce single threaded
# execution.
[[test]]
name = "main"
path = "tests/main.rs"
harness = false


[features]
trace_marker = ["cros_tracing/trace_marker"]
log_page_fault = []

[target.'cfg(unix)'.dependencies]
anyhow = "*"
base = { path = "../base" }
cros_tracing = { path = "../cros_tracing" }
data_model = { path = "../common/data_model" }
jail = { path = "../jail"}
libc = "*"
num_cpus = "*"
once_cell = "*"
remain = "*"
serde = { version = "1", features = [ "derive" ] }
serde_json = "*"
sync = { path = "../common/sync" } # provided by ebuild
tempfile = "*"
thiserror = "*"
userfaultfd-sys = "0.4.2"
userfaultfd = "0.5.0"
vm_memory = { path = "../vm_memory"}

[dev_dependencies]
libtest-mimic = "0.6"
