[package]
name = "swap"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[features]
trace_marker = ["cros_tracing/trace_marker"]

[target.'cfg(unix)'.dependencies]
anyhow = "*"
base = { path = "../base" }
cros_tracing = { path = "../cros_tracing" }
data_model = { path = "../common/data_model" }
libc = "*"
minijail = "*"
num_cpus = "*"
once_cell = "*"
remain = "*"
serde = { version = "1", features = [ "derive" ] }
serde_json = "*"
sync = { path = "../common/sync" } # provided by ebuild
tempfile = "*"
thiserror = "*"
userfaultfd-sys = "0.4.2"
userfaultfd = "0.5.0"
vm_memory = { path = "../vm_memory"}
