[package]
name = "rutabaga_gfx"
version = "0.1.3"
authors = ["The ChromiumOS Authors + Android Open Source Project"]
edition = "2021"
description = "Handling virtio-gpu protocols"
license-file = "LICENSE"

[features]
gfxstream = []
gfxstream_stub = []
virgl_renderer = []
minigbm = []
# Vulkano features are just a prototype and not integrated yet into the ChromeOS build system.
vulkano = ["dep:vulkano"]
x = []

[dependencies]
cfg-if = "1.0.0"
libc = "0.2.116"
remain = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0.23"
zerocopy = { version = "0.8.13", features = ["derive"] }

log = "0.4"

# To build latest Vulkano, change version to git = "https://github.com/vulkano-rs/vulkano.git"
vulkano = { version = "0.33.0", optional = true }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
nix = { version = "0.29", features = ["event", "feature", "fs", "mman", "socket", "uio", "ioctl"] }

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winnt", "handleapi", "processthreadsapi", "winbase"]}

[build-dependencies]
pkg-config = "0.3"
anyhow = "1"

[dev-dependencies]
tempfile = "3"
