[package]
name = "ffmpeg"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
anyhow = "*"
base = { path = "../../base" }
libc = "*"
thiserror = "*"

[build-dependencies]
pkg-config = "*"
