[package]
name = "hypervisor_test_macro"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "^1", features = ["span-locations"] }
quote = "^1"
syn = "2"
rand = "0.8"
