[package]
name = "win_audio"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
audio_streams = { path = "../common/audio_streams"}
base = { path = "../base" }
libc = "*"
win_util = { path = "../win_util" }
winapi = "*"
wio = "*"
sync = { path = "../common/sync" }
thiserror = "*"
metrics = { path = "../metrics"}
once_cell = "1.7.2"