[package]
name = "rutabaga_gfx_ffi"
version = "0.1.1-alpha.1"
authors = ["The ChromiumOS Authors + Android Open Source Project"]
edition = "2021"
license-file = "LICENSE"

[lib]
name = "rutabaga_gfx_ffi"
crate-type = ["cdylib"]

[dependencies]
rutabaga_gfx = { path = "../" }
base = {path = "../../base" }
data_model = {path = "../../common/data_model" }
libc = "0.2.93"

[features]
minigbm = ["rutabaga_gfx/minigbm"]
gfxstream = ["rutabaga_gfx/gfxstream"]
virgl_renderer = ["rutabaga_gfx/virgl_renderer"]
virgl_renderer_next = ["rutabaga_gfx/virgl_renderer_next"]
vulkano = ["rutabaga_gfx/vulkano"]

[patch.crates-io]
minijail = { path = "../../third_party/minijail/rust/minijail" } # ignored by ebuild

[profile.dev]
lto = true
incremental = false

[workspace]
