[package]
name = "cros-codecs"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
vaapi = ["libva"]

[dependencies]
anyhow = { version = "*" }
bitreader = "0.3.6"
bytes = "1.1.0"
enumn = "0.1.4"
log = { version = "0", features = ["release_max_level_debug"] }
thiserror = "1.0.31"
libva = { path = "../libva", optional = true }
downcast-rs = "1.2.0"
crc32fast = "1.3.2"
