[package]
name = "cros_fuzz"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"
include = ["Cargo.toml", "src/*.rs"]

[dependencies]
rand_core = {version = "0.6", features = ["std"]}
libfuzzer-sys = { version = "*", optional = true }
cfg-if = "1.0"

[features]
upstream-fuzz = ["dep:libfuzzer-sys"]


