[package]
name = "metrics"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
kiwi = ["libc", "serde_json", "sync"]

[dependencies]
anyhow = "*"
base = { path = "../base" }
cfg-if = "*"
libc = { version = "*", optional = true }
protobuf = { version = "2.24", features = [ "with-serde" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = { version = "*", optional = true }
sync = { path = "../common/sync", optional = true }

[target.'cfg(windows)'.dependencies]
chrono = { version = "*" }
winapi = { version = "*" }
win_util = { path = "../win_util" }
wmi = { version = "^0.9" }


[build-dependencies]
proto_build_tools = { path = "../proto_build_tools" }
